import os
import tempfile


class TikTokCookies:
    """
    Handles creation and cleanup of a temporary Netscape-format TikTok cookie file.
    """

    def __init__(self, session_id: str | None = None):
        self.session_id = session_id.strip() if session_id else None
        self.cookie_file = None

    def create_cookie_file(self):
        """
        Creates a temp file in Netscape format containing the sessionid cookie (if provided).
        Returns the path to the cookie file.
        """
        lines = ["# Netscape HTTP Cookie File", "# This file was generated by TikSnatch"]

        if self.session_id:
            # Format: domain, flag, path, secure, expiration, name, value
            lines.append(
                f".tiktok.com\tTRUE\t/\tFALSE\t0\tsessionid\t{self.session_id}"
            )

        tmp = tempfile.NamedTemporaryFile(mode="w+", delete=False, suffix=".cookies.txt")
        tmp.write("\n".join(lines) + "\n")
        tmp.flush()
        tmp.close()

        self.cookie_file = tmp.name
        return self.cookie_file

    def cleanup(self):
        """
        Deletes the temporary cookie file if it exists.
        """
        if self.cookie_file and os.path.exists(self.cookie_file):
            os.unlink(self.cookie_file)
            self.cookie_file = None

    def __enter__(self):
        self.create_cookie_file()
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.cleanup()
