name: Build and Push Docker image

on:
  push:
    tags:
      - 'v*'            # e.g. v1.2.3 → versioned release
    branches:
      - 'main'          # optional: stable "latest"
      - 'dev'           # optional: dev branch image
      - 'beta'          # optional: beta branch image

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git tag or branch
        id: extract
        run: |
          REF=${GITHUB_REF#refs/*/}
          echo "ref=$REF" >> $GITHUB_OUTPUT
          TAG=$(echo "$REF" | sed 's/^refs\/tags\///' | sed 's/^refs\/heads\///')
          echo "tagged_version=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            robinmeis/tiksnatch:${{ steps.extract.outputs.ref }}
            robinmeis/tiksnatch:${{ github.ref_name }}-${{ github.sha }}
            ${{ github.ref_type == 'tag' && 'robinmeis/tiksnatch:latest' || '' }}
