name: Run Tests

on:
  push:
    branches: [ "*" ]  # Run on any branch
  pull_request:
    branches: [ "*" ]  # Run on any PR to any branch
  workflow_dispatch:   # Allow manual trigger via GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
