name: Run Tests

on:
  push:
    branches: [ "*" ]  # Run on any branch
  pull_request:
    branches: [ "*" ]  # Run on any PR to any branch
  workflow_dispatch:   # Allow manual trigger via GitHub UI

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests and generate JUnit report
        run: |
          source venv/bin/activate
          pytest --junitxml=report.xml

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: report.xml

      - name: Publish test results to GitHub Checks
        uses: dorny/test-reporter@v1
        if: always()  # Always run even if tests fail
        with:
          name: Pytest Results
          path: report.xml
          reporter: java-junit
