name: Run Tests

on:
  workflow_dispatch:   # Allow manual trigger via GitHub UI

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests and generate JUnit report
        run: |
          source venv/bin/activate
          pytest --junitxml=report.xml

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: report.xml

      - name: Publish test results to GitHub Checks
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: Pytest Results
          path: report.xml
          reporter: java-junit
