name: Build and Push Docker image

on:
  push:
    tags:
      - 'v*'            # e.g. v1.2.3 → versioned release
    branches: [ "*" ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests and generate JUnit report
        run: |
          source venv/bin/activate
          pytest --junitxml=report.xml

      - name: Upload JUnit test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: report.xml

      - name: Publish test results to GitHub Checks
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: Pytest Results
          path: report.xml
          reporter: java-junit

  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Git tag or branch
        id: extract
        run: |
          REF=${GITHUB_REF#refs/*/}
          echo "ref=$REF" >> $GITHUB_OUTPUT
          TAG=$(echo "$REF" | sed 's/^refs\/tags\///' | sed 's/^refs\/heads\///')
          echo "tagged_version=$TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            robinmeis/tiksnatch:${{ steps.extract.outputs.ref }}
            robinmeis/tiksnatch:${{ github.ref_name }}-${{ github.sha }}
            ${{ github.ref_type == 'tag' && 'robinmeis/tiksnatch:latest' || '' }}
